# Generated by Django 6.0.6 on 2026-06-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('categoria', models.CharField(blank=True, choices=[('Consulta Comercial', 'Consulta Comercial'), ('Consulta Técnica', 'Consulta Técnica'), ('Consulta de RRHH', 'Consulta de RRHH'), ('Consulta General', 'Consulta General')], max_length=30, verbose_name='Categoría')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['-fecha'],
            },
        ),
    ]
