# Generated by Django 6.0.6 on 2026-06-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioPermitido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('codigo_validacion', models.CharField(max_length=50, verbose_name='Código de validación')),
            ],
            options={
                'verbose_name': 'Usuario Permitido',
                'verbose_name_plural': 'Usuarios Permitidos',
            },
        ),
    ]
